[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://blog.julienverneaut.com"
  to = "https://www.julienverneaut.com/articles"
  status = 301
  force = true
